### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by Explorare** [aflyhorse/MFGwrapper#1]
---
##   Welcome to MyFleetGirls Client Ver 1.4.8

Ver1.4.8 通信できないbugのfix
Ver1.4.7 proxy動作の変更

十月 13, 2015 2:57:18 下午 com.twitter.finagle.Init$$anonfun$1 apply$mcV$sp
信息: Finagle version 6.25.0 (rev=78909170b7cc97044481274e297805d770465110) built at 20150423-135046
Exception in thread "main" org.jboss.netty.channel.ChannelException: Failed to bind to: localhost/127.0.0.1:8080
    at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:272)
    at com.twitter.finagle.netty3.Netty3Listener$$anon$2.<init>(Netty3Listener.scala:318)
    at com.twitter.finagle.netty3.Netty3Listener.listen(Netty3Listener.scala:298)
    at com.twitter.finagle.server.StdStackServer$$anon$1.<init>(StackServer.scala:210)
    at com.twitter.finagle.server.StdStackServer$class.serve(StackServer.scala:162)
    at com.twitter.finagle.builder.ServerBuilder$$anonfun$codec$2$Server$3.serve(ServerBuilder.scala:219)
    at com.twitter.finagle.builder.ServerBuilder.build(ServerBuilder.scala:462)
    at com.twitter.finagle.builder.ServerBuilder.build(ServerBuilder.scala:408)
    at com.ponkotuy.proxy.FinagleProxy.liftedTree1$1(FinagleProxy.scala:45)
    at com.ponkotuy.proxy.FinagleProxy.<init>(FinagleProxy.scala:40)
    at com.ponkotuy.run.Main$.delayedEndpoint$com$ponkotuy$run$Main$1(Main.scala:17)
    at com.ponkotuy.run.Main$delayedInit$body.apply(Main.scala:14)
    at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
    at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
    at scala.App$$anonfun$main$1.apply(App.scala:76)
    at scala.App$$anonfun$main$1.apply(App.scala:76)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
    at scala.App$class.main(App.scala:76)
    at com.ponkotuy.run.Main$.main(Main.scala:14)
    at com.ponkotuy.run.Main.main(Main.scala)
Caused by: java.net.BindException: Address already in use: bind
    at sun.nio.ch.Net.bind0(Native Method)
    at sun.nio.ch.Net.bind(Unknown Source)
    at sun.nio.ch.Net.bind(Unknown Source)
    at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
    at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
    at org.jboss.netty.channel.socket.nio.NioServerBoss$RegisterTask.run(NioServerBoss.java:193)
    at org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:391)
    at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:315)
    at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
    at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
    at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

**Comment by aflyhorse** [comment]
Your 8080 port might have already been occupied, please double check.

**Comment by Explorare** [comment]
请将此issue标记 `won't fix` 和 `not a bug` label。
